coverage:
  status:
    project:
      default:
        target: 80%    # プロジェクト全体の目標カバレッジ
        threshold: 2%  # 許容される変動幅
    patch:
      default:
        target: 80%    # 新規コードの目標カバレッジ
        threshold: 2%  # 許容される変動幅

ignore:
  - "tests/**/*"      # テストファイル自体は除外
  - "**/*.d.ts"       # 型定義ファイルは除外
  - "cypress/**/*"    # Cypressテストファイルは除外
  - ".next/**/*"      # Next.jsのビルドファイルは除外
  - "public/**/*"     # 静的ファイルは除外
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/mocks/**"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # プルリクエストでカバレッジに変更がなくてもコメントする
  require_base: false
  require_head: true
  show_carryforward_flags: true

github_checks:
  annotations: true      # プルリクエストにアノテーションを追加

flags:
  unittests:
    paths:
      - app/
      - components/
      - lib/
  e2e:
    paths:
      - cypress/
      - tests/e2e/ 