version: '3.8'

services:
  test-db:
    image: postgres:15
    container_name: ppt_translator_test_db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: ppt_translator_test
    ports:
      - "5433:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d ppt_translator_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test-db-data: 