import next from '@next/eslint-plugin-next';
import js from '@eslint/js';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import globals from 'globals';

export default [
  js.configs.recommended,
  {
    plugins: {
      '@next/next': next,
      react: reactPlugin,
      'react-hooks': reactHooksPlugin,
      '@typescript-eslint': tseslint,
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      parser: tsParser,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.jest,
        React: 'readonly',
        IntersectionObserver: 'readonly',
        IntersectionObserverCallback: 'readonly',
        IntersectionObserverInit: 'readonly',
        process: 'readonly',
        module: 'readonly',
        Cypress: 'readonly',
        cy: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        before: 'readonly',
        after: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        FormData: 'readonly',
        FileReader: 'readonly',
        XMLHttpRequest: 'readonly',
        Node: 'readonly',
        Element: 'readonly',
        SVGElement: 'readonly',
        MessageChannel: 'readonly',
        exports: 'readonly',
        Iterator: 'readonly',
        trustedTypes: 'readonly',
        MSApp: 'readonly',
        __REACT_DEVTOOLS_GLOBAL_HOOK__: 'readonly',
        __MOBX_DEVTOOLS_GLOBAL_HOOK__: 'readonly',
        NodeJS: 'readonly',
        HeadersInit: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@next/next/no-html-link-for-pages': 'warn',
      'react/prop-types': 'off',
      'react/react-in-jsx-scope': 'off',
      'react-hooks/rules-of-hooks': 'warn',
      'react-hooks/exhaustive-deps': 'off',
      'no-prototype-builtins': 'warn',
      'no-undef': 'error',
      'no-useless-escape': 'warn',
      'no-empty': 'warn',
      'no-constant-binary-expression': 'warn',
      'no-unsafe-finally': 'warn',
      'no-cond-assign': 'warn',
      'no-func-assign': 'warn',
      'valid-typeof': 'warn',
      'no-fallthrough': 'warn',
      'getter-return': 'warn',
      'no-misleading-character-class': 'warn',
      'no-sparse-arrays': 'warn',
      'no-redeclare': 'warn',
      'no-control-regex': 'warn',
      'no-unreachable': 'warn',
    },
    files: ['**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx'],
    ignores: [
      'next.config.cjs',
      'node_modules/**',
      '.next/**',
      'out/**',
      'dist/**',
      'build/**',
      '.cache/**',
      '.swc/**',
      '.venv/**',
      'venv/**',
      'cypress/**',
      '.prettierrc.cjs',
      'babel.config.js',
      'jest.config.js',
      'next.config.js',
      'postcss.config.js',
      'tailwind.config.js',
      'eslint.config.js',
      '*.config.js',
      '*.config.cjs',
      '*.min.js',
      '*.bundle.js',
      'prisma/dist/**',
      'scripts/**',
      'public/**',
      'coverage/**',
      'tmp/**',
      'dest/**',
      '.vercel/**',
      'reports/**',
      '.cursor/**',
      '.github/**',
      '.swc/**',
      'python_backend/**',
      'uploads/**',
      '.next/static/chunks/webpack-*.js',
      '.next/static/chunks/*-*.js',
    ],
  },
  {
    files: [
      'app/**/*.js',
      'app/**/*.jsx',
      'app/**/*.ts',
      'app/**/*.tsx',
      'components/**/*.js',
      'components/**/*.jsx',
      'components/**/*.ts',
      'components/**/*.tsx',
      'lib/**/*.js',
      'lib/**/*.jsx',
      'lib/**/*.ts',
      'lib/**/*.tsx',
      'types/**/*.js',
      'types/**/*.jsx',
      'types/**/*.ts',
      'types/**/*.tsx',
    ],
    rules: {
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@next/next/no-html-link-for-pages': 'warn',
      'react/prop-types': 'off',
      'react/react-in-jsx-scope': 'off',
      'react-hooks/rules-of-hooks': 'warn',
      'react-hooks/exhaustive-deps': 'off',
      'no-prototype-builtins': 'warn',
      'no-undef': 'error',
      'no-useless-escape': 'warn',
      'no-empty': 'warn',
      'no-constant-binary-expression': 'warn',
      'no-unsafe-finally': 'warn',
      'no-cond-assign': 'warn',
      'no-func-assign': 'warn',
      'valid-typeof': 'warn',
      'no-fallthrough': 'warn',
      'getter-return': 'warn',
      'no-misleading-character-class': 'warn',
      'no-sparse-arrays': 'warn',
      'no-redeclare': 'warn',
      'no-control-regex': 'warn',
    },
  },
];
